_extends: sites/fiwiki.yml
name: Heinäkuun lähdetalkoot %(year)d
pages:
    base: Wikipedia:Heinäkuun lähdetalkoot/
    default: Wikipedia:Heinäkuun lähdetalkoot/%(year)d
contestPages:
    footer: ""
templates:
    infobox:
        name: Viikon kilpailun tietolaatikko
plot:
    datafile: plots/fi-hl.json
    figname: plots/Fiwp Heinäkuun lähdetalkoot %(year)d.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{no|1=Resultater for [[:fi:Wikipedia:Heinäkuun lähdetalkoot/%(year)s|Heinäkuun lähdetalkoot %(year)s]]}}
                          {{en|1=Results from the article writing contest [[:fi:Wikipedia:Heinäkuun lähdetalkoot/%(year)s|Heinäkuun lähdetalkoot%(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Heinäkuun lähdetalkoot]]
