_extends: sites/fiwiki.yml
name: Elokuun kuvitustalkoot %(year)d
pages:
    base: Wikipedia:Elokuun kuvitustalkoot/
    default: Wikipedia:Elokuun kuvitustalkoot/%(year)d
contestPages:
    resultsSection: Tulokset
    participantsSection: Osallistujat
    footer: "[[Luokka:Elokuun kuvitustalkoot|%(year)d]]"
templates:
    infobox:
        name: Viikon kilpailun tietolaatikko
plot:
    datafile: plots/fi-ek.json
    figname: plots/Fiwp Elokuun kuvitustalkoot %(year)d.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{fi|1=[[:fi:%(pagename)s|Vuoden %(year)s elokuun kuvitustalkoiden tilanne]]}}
                          {{en|1=Results from the article writing contest [[:fi:%(pagename)s|Elokuun kuvitustalkoot %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Elokuun kuvitustalkoot]]
