# Configuration file for "Ukens konkurranse" @ nowiki
_extends: sites/nowiki.yml
contest_type: weekly
pages:
    base: Wikipedia:Konkurranser/Ukens konkurranse
    default: Wikipedia:Konkurranser/Ukens konkurranse %(year)d-%(week)02d
    redirect: WP:UK
contestPages:
    footer: "{{ukens konkurranse %(year)s}}\n[[Kategori:Artikkelkonkurranser]]"
templates:
    contestlist:
        name: Ukens konkurranse
    infobox:
        name: Infoboks ukens konkurranse
award_messages:
    winner_template: '{{UK vinner|år=%(year)s|uke=%(week)s|%(awards)s}}'
    participant_template: '{{UK deltaker|år=%(year)s|uke=%(week)s|%(awards)s}}'
    organizer_template: '{{UK arrangør|år=%(year)s|uke=%(week)s|%(awards)s|visuk=nei}}'

plot:
    datafile: 'plots/Nowp Ukens konkurranse %(year)d-%(week)02d.json'
    figname: 'plots/Nowp Ukens konkurranse %(year)d-%(week)02d.svg'
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{no|1=Resultater for [[:no:%(pagename)s|Ukens konkurranse uke %(week)s, %(year)s]]}}
                          {{en|1=Results from the weekly article writing contest at Norwegian Bokmål/Nynorsk Wikipedia [[:no:%(pagename)s|week %(week)s, %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Ukens konkurranse %(year)s]]
