_extends: sites/euwiki.yml
pages:
    base: 'Atari:Hezkuntza/Lehiaketak'
    default: 'Atari:Hezkuntza/Lehiaketak/%(year)d/%(month)02d'
    redirect:
      - 'Atari:Hezkuntza/Lehiaketak'
      - 'WP:L'
plot:
    datafile: plots/Lehiaketak %(year)d-%(month)02d.json
    figname: plots/Lehiaketak %(year)d-%(month)02d.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{en|1=Results from the monthly article writing contest at Basque Wikipedia [[:eu:%(pagename)s|%(year)s-%(month)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}

        == {{int:license-header}} ==
        {{PD-self}}

        [[Category:Lehiaketak]]
