locale: [nb_NO, no_NO]
rollbar_token: 88f5bd483f7348ea8b0564449c8d77cd
server_timezone: UTC
wiki_timezone: Europe/Oslo
homesite: no.wikipedia.org
default_prefix: "no"
plot:
    datafile: 'plots/Nowp Ukens konkurranse %(year)d-%(week)02d.json'
    figname: 'plots/Nowp Ukens konkurranse %(year)d-%(week)02d.svg'
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{no|1=Resultater for [[:no:%(pagename)s|Ukens konkurranse uke %(week)s, %(year)s]]}}
                          {{en|1=Results from the weekly article writing contest at Norwegian Bokmål/Nynorsk Wikipedia [[:no:%(pagename)s|week %(week)s, %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Ukens konkurranse %(year)s]]
othersites:
    - nn.wikipedia.org
    - se.wikipedia.org
    # - commons.wikimedia.org
    # - www.wikidata.org
awards:
    blå: { file: Article blue.svg, winner: true }
    rød: { file: Article red.svg, winner: true }
    gul: { file: Article yellow.svg, organizer: true }
    oransj: { file: Article orange.svg, winner: true }
    orange: { file: Article orange.svg, winner: true }
    grønn: { file: Article green.svg }
    grå: { file: Article grey.svg }
    lyslilla: { file: Article MediumPurple.svg }
    lilla: { file: Article purple.svg }
    brun: { file: Article brown.svg }
award_messages:
    winner_template: '{{UK vinner|år=%(year)s|uke=%(week)s|%(award)s=ja}}'
    participant_template: '{{UK deltaker|år=%(year)s|uke=%(week)s|%(award)s=ja}}'
    organizer_template: '{{UK arrangør|år=%(year)s|uke=%(week)s|%(award)s=ja|visuk=nei}}'
templates:
    botinfo: Ukens konkurranse robotinfo
    status: Ukens konkurranse status
    commonargs:
        year: år
        week: uke
        week2: ukefler
        yes: ja
        no: nei
    infobox:
        name: Infoboks ukens konkurranse
        status: status
        start: start
        end: slutt
        organizer: leder
        winner: vinner
    suspended:
        name: UK bruker suspendert
    disqualified:
        name: UK bidrag diskvalifisert
    penalty:
        name: UK poengtrekk
    bonus:
        name: UK poeng
    contestlist:
        name: Ukens konkurranse-liste
    rule:
        name: Ukens konkurranse poeng
        new: ny
        redirect: omdirigering
        refsectionfi: refsectionfi
        qualified: kvalifisert
        contrib: endring
        byte: byte
        word: ord
        maxpoints: makspoeng
        site: nettsted
        image: bilde
        external_link: ekstern lenke
        ref: ref
        templateremoval: malfjerning
        bytebonus: bytebonus
        wordbonus: ordbonus
        alias: alias
        own: egetbilde
        ownwork: egetverk
        maxinitialcount: maksantallinnledningsvis
    filters: !include filters.no.yml
pages:
    base: Wikipedia:Konkurranser/Ukens konkurranse
    default: Wikipedia:Konkurranser/Ukens konkurranse %(year)d-%(week)02d
    redirect: WP:UK
contestPages:
    resultsSection: Resultater
    participantsSection: 'Delta[kg]ere'
    footer: "{{ukens konkurranse %(year)s}}\n[[Kategori:Artikkelkonkurranser]]"
awardstatus:
    pagename: Bruker:UKBot/Premieutsendelse
    wait: Venter
    send: Send ut
    sent: Sendt
ignore:
    - Tilbakestilte endring # MediaWiki:Revertpage/nb
    - Attenderulla endring  # MediaWiki:Revertpage/nn
    - rievdadusat sihkkojuvvui ja siidu  # MediaWiki:Revertpage/se
    - Reverted edits by  # MediaWiki:Revertpage/en
    - Fjerner revisjon # MediaWiki:Undo-summary/nb
    - Rullar attende versjon # MediaWiki:Undo-summary/nn
    - Undo revision # MediaWiki:Revertpage/en
    - clientsitelink-update  # Wikidata: Page moved from .. to ..
    - clientsitelink-remove  # Wikidata: Removed sitelink
