locale: fi_FI
rollbar_token: 88f5bd483f7348ea8b0564449c8d77cd
server_timezone: UTC
wiki_timezone: Europe/Helsinki
homesite: fi.wikipedia.org
default_prefix: fi
plot:
    datafile: plots/Punaisten linkkien naiset %(year)d.json
    figname: plots/Punaisten linkkien naiset %(year)d.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{en|1=Results from the article writing contest [[:fi:%(pagename)s|Punaisten linkkien naiset %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Wikipedia contests of Finnish Wikipedia]]
awards:
    sininen: { file: Article blue.svg, winner: true }
    punainen: { file: Article red.svg, winner: true }
    keltainen: { file: Article yellow.svg, organizer: true }
    oranssi: { file: Article orange.svg }
    vihreä: { file: Article green.svg }
    hopea: { file: Article grey.svg }
    vaaleanvioletti: { file: Article MediumPurple.svg }
    violetti: { file: Article purple.svg }
    ruskea: { file: Article brown.svg }
templates:
    botinfo: Viikon kilpailu robotti-info
    status: Viikon kilpailu tilanne
    commonargs:
        year: vuosi
        week: viikko
        week2: loppuviikko
        yes: kyllä
        no: ei
    infobox:
        name: UKB inline infobox
        status: tilanne
        start: alkaa
        end: loppuu
        organizer: järjestäjät
        winner: voittaja
    suspended:
        name: VK osallistuja hylätty
    disqualified:
        name: VK muokkaus hylätty
    penalty:
        name: VK pisteidenhylkäys
    bonus:
        name: VK bonus
    contestlist:
        name: Viikon kilpailu luettelo
    rule:
        name: Viikon kilpailu pisteet
        new: uusi
        qualified: NOT-IN-USE
        contrib: NOT-IN-USE
        redirect: ohjaus
        refsectionfi: refsectionfi
        byte: tavu
        word: sana
        maxpoints: makspisteet
        site: site
        image: kuva
        external_link: aiheesta muualla
        ref: ref
        templateremoval: mallineen poisto
        bytebonus: tavubonus
        wordbonus: sanabonus
        alias: alias
        own: oma
        ownwork: oma teos
        maxinitialcount: makskuvienmäärä
    filters: !include filters.fi.yml
pages:
    catignore: Käyttäjä:UKBot/cat-ignore
    base: Wikiprojekti:Punaisten linkkien naiset
    default: Wikiprojekti:Punaisten linkkien naiset
contestPages:
    participantsSection: Osallistujat
    footer: ""
awardstatus:
    pagename: Käyttäjä:UKBot/Premieutsendelse
    wait: Venter
    send: Send ut
    sent: Sendt
ignore:
    - muokkaukset kumottiin ja sivu palautettiin # MediaWiki:Revertpage
    - ^Hylättiin (viimeisin tekstimuutos|viimeisimmät .* tekstimuutosta) # MediaWiki:Revreview-reject-summary-cur/fi
    - ^Kumottu muokkaus # MediaWiki:Undo-summary/fi
    - clientsitelink-update  # Wikidata: Page moved from .. to ..
    - clientsitelink-remove  # Wikidata: Removed sitelink
