_extends: sites/fiwiki.yml
othersites:
    - ast.wikipedia.org
    - az.wikipedia.org
    - bg.wikipedia.org
    - bxr.wikipedia.org
    - ca.wikipedia.org
    - de.wikipedia.org
    - en.wikipedia.org
    - eo.wikipedia.org
    - es.wikipedia.org
    - et.wikipedia.org
    - eu.wikipedia.org
    - fr.wikipedia.org
    - hu.wikipedia.org
    - lv.wikipedia.org
    - nl.wikipedia.org
    - no.wikipedia.org
    - oc.wikipedia.org
    - olo.wikipedia.org
    - ru.wikipedia.org
    - se.wikipedia.org
    - sv.wikipedia.org
    - myv.wikipedia.org
    - ja.wikipedia.org
    - pt.wikipedia.org
    - zh.wikipedia.org
    - vep.wikipedia.org
pages:
    base: "Wikiprojekti:Suomi 100"
    default: Wikiprojekti:Suomi 100/International Challenge
contestPages:
    resultsSection: Results
    participantsSection: Participants
    footer: "{{Viikon kilpailut %(year)s}}\n[[Luokka:Viikon kilpailut %(year)s]]"
templates:
    infobox:
        name: UKB no infobox
plot:
    datafile: ../plots/fi-100.json
    figname: Suomi 100.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{en|1=Results from the article writing contest [[:fi:%(pagename)s|Suomi 100]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Viikon kilpailu]]
