_extends: sites/fiwiki.yml
name: Punaisten linkkien naiset %(year)s
othersites:
    - se.wikipedia.org
pages:
    catignore: Käyttäjä:UKBot/cat-ignore
    base: Wikiprojekti:Punaisten linkkien naiset
    default: Wikiprojekti:Punaisten linkkien naiset/%(year)s
contestPages:
    participantsSection: Osallistujat
    footer: ""
templates:
    infobox:
        name: UKB inline infobox
plot:
    datafile: plots/Punaisten linkkien naiset %(year)d.json
    figname: plots/Punaisten linkkien naiset %(year)d.svg
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{en|1=Results from the article writing contest [[:fi:%(pagename)s|Punaisten linkkien naiset %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Wikipedia contests of Finnish Wikipedia]]
