---
name: Ukens konkurranse kriterium
params:
    _all:
        params:
            site: nettsted
    new: 
        name: ny
        params:
            redirects: omdirigeringer
    existing:
        name: eksisterende
    template:
        name: mal
    bytes:
        name: bytes
    category:
        name: kategori
        ignore_page: Bruker:UKBot/cat-ignore
        params:
            ignore: utelat
            maxdepth: maksdybde
    backlink:
        name: tilbakelenke
        params:
            include_langlinks: true
    forwardlink:
        name: fremlenke
    pages:
        name: enkeltsider
    namespace:
        name: navnerom
        params:
            site: nettsted
    sparql:
        name: sparql  # as in {{ ukb criterion | sparql }}
        params:
            query: spørring    # as in {{ ukb criterion | sparql | query=... }}
